# Generated by Django 2.2.3 on 2021-02-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rulebook', '0028_damagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('CON', models.IntegerField(default=10)),
                ('STR', models.IntegerField(default=0)),
                ('FRT', models.IntegerField(default=0)),
                ('DEX', models.IntegerField(default=10)),
                ('AGI', models.IntegerField(default=0)),
                ('FIN', models.IntegerField(default=0)),
                ('INT', models.IntegerField(default=10)),
                ('ING', models.IntegerField(default=0)),
                ('REC', models.IntegerField(default=0)),
                ('WIL', models.IntegerField(default=10)),
                ('DEV', models.IntegerField(default=0)),
                ('COU', models.IntegerField(default=0)),
                ('INS', models.IntegerField(default=10)),
                ('CHA', models.IntegerField(default=0)),
                ('CRE', models.IntegerField(default=0)),
                ('INI_mod', models.IntegerField()),
                ('PER_mod', models.IntegerField()),
                ('MPA_mod', models.IntegerField()),
                ('MEL_mod', models.IntegerField()),
                ('RAN_mod', models.IntegerField()),
                ('PAR_mod', models.IntegerField()),
                ('FOR_mod', models.IntegerField()),
                ('CAR_mod', models.IntegerField()),
                ('DDG_mod', models.IntegerField()),
                ('Health_mod', models.IntegerField()),
                ('Status_mod', models.IntegerField()),
                ('Mana_mod', models.IntegerField()),
                ('race', models.ForeignKey(on_delete='Cascade', to='rulebook.Race')),
            ],
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('healed', models.IntegerField()),
                ('state', models.CharField(choices=[('F', 'Fresh'), ('T', 'Treated'), ('O', 'Old')], default='F', max_length=1)),
                ('owner', models.ForeignKey(on_delete='Cascade', related_name='wounds', to='sheet.Character')),
                ('type', models.ForeignKey(on_delete='Cascade', to='rulebook.DamageType')),
            ],
        ),
        migrations.CreateModel(
            name='SkillInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('granted', models.IntegerField()),
                ('base', models.ForeignKey(blank=True, on_delete='Cascade', to='rulebook.Skill')),
                ('owner', models.ForeignKey(on_delete='Cascade', related_name='skills', to='sheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('base', models.ForeignKey(blank=True, on_delete='Cascade', to='rulebook.Ability')),
                ('owner', models.ForeignKey(on_delete='Cascade', related_name='abilities', to='sheet.Character')),
            ],
        ),
    ]
