# Generated by Django 2.2.3 on 2021-02-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='Status_mod',
        ),
        migrations.AddField(
            model_name='character',
            name='Stamina_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='CAR_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='DDG_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='FOR_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='Health_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='INI_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='MEL_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='MPA_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='Mana_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='PAR_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='PER_mod',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='RAN_mod',
            field=models.IntegerField(default=10),
        ),
    ]
