# Generated by Django 2.2.3 on 2021-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0028_damagetype'),
        ('sheet', '0002_auto_20210222_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('expiration', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=models.CASCADE, related_name='notes', to='sheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('base', models.ForeignKey(blank=True, on_delete=models.CASCADE, to='rulebook.Item')),
                ('container', models.ForeignKey(blank=True, on_delete=models.CASCADE, related_name='content', to='sheet.InventoryItem')),
                ('owner', models.ForeignKey(blank=True, on_delete=models.CASCADE, related_name='inventory', to='sheet.Character')),
            ],
        ),
    ]
