# Generated by Django 2.2.3 on 2021-02-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_inventoryitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Health',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='Mana',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='Stamina',
            field=models.IntegerField(default=10),
        ),
    ]
