# Generated by Django 2.2.3 on 2021-02-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_auto_20210223_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='AGI',
            new_name='AGI_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='CHA',
            new_name='CHA_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='COU',
            new_name='COU_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='CRE',
            new_name='CRE_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='DEV',
            new_name='DEV_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='FIN',
            new_name='FIN_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='FRT',
            new_name='FRT_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='ING',
            new_name='ING_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='REC',
            new_name='REC_mod',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='STR',
            new_name='STR_mod',
        ),
    ]
