# Generated by Django 2.2.3 on 2021-02-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20210224_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityinstance',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='rulebook.Ability'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='rulebook.Item'),
        ),
        migrations.AlterField(
            model_name='skillinstance',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='rulebook.Skill'),
        ),
    ]
