# Generated by Django 2.2.3 on 2021-02-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_auto_20210226_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='text',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
