# Generated by Django 3.1.7 on 2021-03-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0011_auto_20210227_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilityinstance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.abilityinstance'),
        ),
    ]
