# Generated by Django 3.1.7 on 2021-03-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0012_abilityinstance_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityinstance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='sheet.character'),
        ),
        migrations.AlterField(
            model_name='abilityinstance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sheet.abilityinstance'),
        ),
    ]
