# Generated by Django 3.1.7 on 2021-03-07 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0028_damagetype'),
        ('sheet', '0013_auto_20210307_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.race'),
        ),
    ]
