# Generated by Django 3.1.7 on 2021-03-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0028_damagetype'),
        ('sheet', '0014_auto_20210307_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='CAR_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='DDG_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='FOR_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='Health_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='INI_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='MEL_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='MPA_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='Mana_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='PAR_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='PER_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='RAN_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='Stamina_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WeaponInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.weapon')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.skill')),
            ],
        ),
    ]
