# Generated by Django 3.1.7 on 2021-03-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0015_auto_20210311_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='sheet.character'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='sheet.character'),
        ),
    ]
