# Generated by Django 3.1.7 on 2021-03-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0017_auto_20210312_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponinstance',
            old_name='base',
            new_name='base_weapon',
        ),
        migrations.RemoveField(
            model_name='weaponinstance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weaponinstance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weaponinstance',
            name='owner',
        ),
        migrations.AddField(
            model_name='weaponinstance',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weaponinstance',
            name='force',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weaponinstance',
            name='hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weaponinstance',
            name='inventoryitem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sheet.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weaponinstance',
            name='isRanged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weaponinstance',
            name='parry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weaponinstance',
            name='range',
            field=models.IntegerField(default=0),
        ),
    ]
