# Generated by Django 3.1.7 on 2021-03-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0019_auto_20210314_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sheet.inventoryslot'),
        ),
    ]
