# Generated by Django 3.1.7 on 2021-03-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0020_auto_20210314_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sheet.character'),
        ),
    ]
