# Generated by Django 2.2.3 on 2020-07-06 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Ability'),
        ),
    ]
