# Generated by Django 2.2.3 on 2020-07-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0004_ability_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
