# Generated by Django 2.2.3 on 2020-07-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0005_auto_20200708_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('content_short', models.CharField(blank=True, max_length=250, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Rule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
