# Generated by Django 2.2.3 on 2020-07-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0008_auto_20200710_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='DELETED',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='DELETED',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
