# Generated by Django 2.2.3 on 2020-07-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0010_auto_20200710_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='requires',
        ),
        migrations.CreateModel(
            name='AbilityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=200)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rulebook.Ability')),
                ('requires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rulebook.Ability')),
            ],
        ),
    ]
