# Generated by Django 2.2.3 on 2020-07-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0011_auto_20200710_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='requires',
            field=models.ManyToManyField(blank=True, related_name='_ability_requires_+', through='rulebook.AbilityRequirement', to='rulebook.Ability'),
        ),
    ]
