# Generated by Django 2.2.3 on 2020-07-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0012_ability_requires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent+', to='rulebook.Ability'),
        ),
    ]
