# Generated by Django 2.2.3 on 2020-07-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0013_auto_20200710_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='requires',
            field=models.ManyToManyField(blank=True, related_name='required', through='rulebook.AbilityRequirement', to='rulebook.Ability'),
        ),
    ]
