# Generated by Django 2.2.3 on 2020-07-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0015_auto_20200710_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityrequirement',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='rulebook.Ability'),
        ),
        migrations.AlterField(
            model_name='abilityrequirement',
            name='requires',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rulebook.Ability'),
        ),
    ]
