# Generated by Django 2.2.3 on 2020-07-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0016_auto_20200710_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(default=None, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('density', models.FloatField(default=1.0)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='flavor',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rulebook.Substance')),
                ('category', models.CharField(max_length=200)),
                ('deflection', models.FloatField(default=0)),
                ('padding', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('rulebook.substance',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(default=None, null=True)),
                ('skill', models.CharField(blank=True, max_length=45, null=True)),
                ('damage_base', models.IntegerField(default=0)),
                ('damage_dice', models.IntegerField(default=0)),
                ('dice_type', models.CharField(default='d6', max_length=3)),
                ('damage_type', models.CharField(choices=[('P', 'Piercing'), ('B', 'Blunt')], default='Piercing', max_length=3)),
                ('force', models.IntegerField(default=0)),
                ('force_modifier', models.IntegerField(default=1)),
                ('parry', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=6)),
                ('cost_reload', models.IntegerField(default=3)),
                ('weight', models.IntegerField(default=500)),
                ('min_str', models.IntegerField(blank=True, default=None, null=True)),
                ('min_range', models.IntegerField(blank=True, default=None, null=True)),
                ('max_range', models.IntegerField(blank=True, default=None, null=True)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(default=None, null=True)),
                ('CON', models.CharField(max_length=200)),
                ('STR', models.CharField(max_length=200)),
                ('FRT', models.CharField(max_length=200)),
                ('DEX', models.CharField(max_length=200)),
                ('AGI', models.CharField(max_length=200)),
                ('FIN', models.CharField(max_length=200)),
                ('INT', models.CharField(max_length=200)),
                ('ING', models.CharField(max_length=200)),
                ('REC', models.CharField(max_length=200)),
                ('WIL', models.CharField(max_length=200)),
                ('DEV', models.CharField(max_length=200)),
                ('COU', models.CharField(max_length=200)),
                ('INS', models.CharField(max_length=200)),
                ('CHA', models.CharField(max_length=200)),
                ('CRE', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(default=None, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('weight', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(default=None, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enchantment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(default=None, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('strength', models.CharField(max_length=200)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(default=None, null=True)),
                ('CON', models.CharField(max_length=200)),
                ('STR', models.CharField(max_length=200)),
                ('FRT', models.CharField(max_length=200)),
                ('DEX', models.CharField(max_length=200)),
                ('AGI', models.CharField(max_length=200)),
                ('FIN', models.CharField(max_length=200)),
                ('INT', models.CharField(max_length=200)),
                ('ING', models.CharField(max_length=200)),
                ('REC', models.CharField(max_length=200)),
                ('WIL', models.CharField(max_length=200)),
                ('DEV', models.CharField(max_length=200)),
                ('COU', models.CharField(max_length=200)),
                ('INS', models.CharField(max_length=200)),
                ('CHA', models.CharField(max_length=200)),
                ('CRE', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(default=None, null=True)),
                ('deflection', models.FloatField(default=0)),
                ('padding', models.FloatField(default=0)),
                ('text', models.CharField(max_length=2000)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
