# Generated by Django 2.2.3 on 2020-07-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0019_auto_20200711_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ('root_id', 'index')},
        ),
        migrations.AlterField(
            model_name='rule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rulebook.Rule'),
        ),
    ]
