# Generated by Django 2.2.3 on 2020-07-15 20:20

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0020_auto_20200713_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateField(blank=True, default=None, null=True)),
                ('isPseudo', models.BooleanField(default=False)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
