# Generated by Django 2.2.3 on 2020-07-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0021_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Skill'),
        ),
    ]
