# Generated by Django 2.2.3 on 2020-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0022_auto_20200716_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='cost_reload',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
