# Generated by Django 2.2.3 on 2020-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0024_auto_20200716_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
