# Generated by Django 2.2.3 on 2020-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0026_auto_20200717_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
