# Generated by Django 2.2.3 on 2021-02-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0027_auto_20200907_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=2000, null=True)),
                ('flavor', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETED', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('expansion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rulebook.Expansion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
